LearningLog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_logs.urls')),
]

learning_logs/urls.py
from django.urls import path
from . import views

app_name = 'learning_logs'
urlpatterns = [
    # Main page
    path('', views.index, name='index'),
    # Page with all topics
    path('topics/', views.topics, name='topics'),
    # Page for a specific topic
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # Page to add new topic
    path('new_topic/', views.new_topic, name='new_topic'),
    # Page to add new entry to a topic
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # Page to edit existing entry
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),
]

users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    # Default url for auth
    path('', include('django.contrib.auth.urls')),
    # Page for registrations
    path('register/', views.register, name='register'),
    path('registered/', views.registered, name='registered')
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.text


class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        if len(self.text) > 50:
            return f'{self.text[:50]}...'
        return self.text

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Topic, Entry


class TopicForm(forms.ModelForm):

    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.TextInput({'placeholder': 'Topic name'})}


class EntryForm(forms.ModelForm):

    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .forms import TopicForm, EntryForm
from .models import Topic, Entry


def index(request):
    return render(request, 'learning_logs/index.html')


@login_required
def topics(request):
    topics_ = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics_}
    return render(request, 'learning_logs/topics.html', context)


@login_required
def topic(request, topic_id):
    topic_ = Topic.objects.get(id=topic_id)
    if topic_.owner != request.user:
        raise Http404

    entries = topic_.entry_set.order_by('-date_added')
    context = {'topic': topic_, 'entries': entries}

    return render(request, 'learning_logs/topic.html', context)


@login_required
def new_topic(request):
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic_ = form.save(commit=False)
            new_topic_.owner = request.user
            new_topic_.save()
            return redirect('learning_logs:topics')

    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


@login_required
def new_entry(request, topic_id):
    topic_ = Topic.objects.get(id=topic_id)
    if topic_.owner != request.user:
        raise Http404

    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry_ = form.save(commit=False)
            new_entry_.topic = topic_
            new_entry_.save()
            return redirect('learning_logs:topic', topic_id=topic_id)

    context = {'topic': topic_, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic_ = entry.topic
    if topic_.owner != request.user:
        raise Http404

    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic_.id)

    context = {'entry': entry, 'topic': topic_, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('users:registered')

    context = {'form': form}
    return render(request, 'registration/register.html', context)


def registered(request):
    return render(request, 'registration/registered.html')

templates/learning_logs/base.html
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Learning Log</title>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
        <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Learning Log</a>
        <button class="navbar-toggler"
                type="button"
                data-toggle="collapse"
                data-target="#navbarCollapse"
                aria-controls="navbarCollapse"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'learning_logs:topics' %}">Topics</a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <span class="navbar-text">Hello, {{ user.username }}</span>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <main role="main" class="container">
        <section class="pb-2 mb-2 border-bottom">
            {% block pageheader %}{% endblock pageheader %}
        </section>
        <section>
            {% block content %}{% endblock content %}
        </section>
    </main>
</body>
</html>

templates/learning_logs/edit_entry.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap4 %}

{% block pageheader %}
    <h2>Edit entry <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h2>
{% endblock %}

{% block content %}

    <form method="post" action="{% url 'learning_logs:edit_entry' entry.id %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">Save changes</button>
        {% endbuttons %}
    </form>

{% endblock content %}

templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block pageheader %}
    <div class="jumbotron">
        {% if user.is_authenticated %}
            <h1 class="display-4">
                Welcome back, {{ user.username }}
            </h1>
            <a class="btn btn-lg btn-primary mt-3" href="{% url 'learning_logs:topics' %}" role="button">
                Continue learning &raquo;
            </a>
        {% else %}
            <h1 class="display-3">
                Track your learning
            </h1>
            <p class="lead">
                Make your own Learning Log, and keep a list of the topics you're learning about. Whenever you learn
                something new about a topic, make an entry summarizing what you've learned
            </p>
            <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}" role="button">
                Register &raquo;
            </a>
        {% endif %}
    </div>
{% endblock pageheader %}

templates/learning_logs/new_entry.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap4 %}

{% block pageheader %}
    <h2><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h2>
{% endblock %}

{% block content %}

    <form method="post" action="{% url 'learning_logs:new_entry' topic.id %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">Add entry</button>
        {% endbuttons %}
    </form>

{% endblock content %}

templates/learning_logs/new_topic.html
{% extends 'learning_logs/base.html' %}
{% load bootstrap4 %}

{% block pageheader %}
    <h2>Add a new topic</h2>
{% endblock %}

{% block content %}

    <form method="post" action="{% url 'learning_logs:new_topic' %}" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">Add topic</button>
        {% endbuttons %}
    </form>

{% endblock content %}

templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block pageheader %}
    <h3>{{ topic }}</h3>
{% endblock pageheader %}

{% block content %}

    <p>
        <a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a>
    </p>

    {% for entry in entries %}
        <div class="card mb-3">
            <h4 class="card-header">
                {{ entry.date_added|date:'M d, Y H:i' }}
                <small><a href="{% url 'learning_logs:edit_entry' entry.id %}">edit</a></small>
            </h4>
            <div class="card-body">
                {{ entry.text|linebreaks }}
            </div>
        </div>
    {% empty %}
        <p>There are no entries for this topic yet.</p>
    {% endfor %}

{% endblock content %}

templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block pageheader %}
    <h1>Topics</h1>
{% endblock pageheader %}

{% block content %}


    {% if topics %}
        <ul class="list-group mt-3">
            {% for topic in topics %}
                <li class="list-group-item"><h3>
                    <a href={% url 'learning_logs:topic' topic.id %}>{{ topic }}</a>
                </h3></li>
            {% endfor %}
        </ul>
    {% else %}
        <h3>No topics have been added yet.</h3>
    {% endif %}

    <a role="button" class="btn btn-primary mt-3" href="{% url 'learning_logs:new_topic' %}">Add a new topic</a>

{% endblock content %}